# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

# This workflow will periodically check .NET nanoFramework dependencies and updates them in the repository it's running.

name: Update dependencies (round 4)

on:
  schedule:
    # At 03:30 UTC.
    # Set 30 min apart from round three to allow enough time for any changes to propagate.
    - cron:  '30 03 * * Mon,Wed'
  repository_dispatch:
    types: update-dependencies
  workflow_dispatch:

jobs:
  update-nuget-dependencies:
    name: nanoFramework
    uses: nanoframework/nf-tools/.github/workflows/update-dependencies.yml@main
    secrets: inherit
    with:
      timeout-minutes: 120 # Non default as IoT devices has lots of solutions to update (taking into account PR merge and build branch)!
      solutionsToCheck: '*.sln'
      workingDirectory: devices
      branchToPr: 'develop'
      # these projects are in other update rounds or in the works (genereted devices)
      exclusionList: 'Card,CharacterLcd,Ft6xx6x,ShiftRegister,NumberHelper,System.Buffers.Binary.BinaryPrimitives,Multiplexing,System.Device.Model,System.Diagnostics.Stopwatch,System.Drawing,System.Numerics,WeatherHelper,BoardLed,BuildHat,Common,Display,Ft232H,Ili9341,Pca9685,RGBLedMatrix,Scd4x,SensorHub,SocketCan,Ssd1351,StUsb4500,UFireIse'
