# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

# This workflow will periodically check .NET nanoFramework dependencies and updates them in the repository it's running.

name: Update dependencies (round 5)

on:
  schedule:
    # At 05:45 UTC.
    # Set 3 hours apart from round four to allow enough time for any changes to propagate.
    - cron:  '45 05 * * Mon,Wed'
  repository_dispatch:
    types: update-dependencies
  workflow_dispatch:

jobs:
  update-nuget-dependencies:
    name: nanoFramework
    uses: nanoframework/nf-tools/.github/workflows/update-dependencies.yml@main
    secrets: inherit
    with:
      timeout-minutes: 15 # It should not take longer!
      workingDirectory: devices
      branchToPr: 'develop'      
      solutionsToCheck: |
        Ft6xx6x.sln
