# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

# This workflow will periodically check .NET nanoFramework dependencies and updates them in the repository it's running.

name: Update dependencies (round 3)

on:
  schedule:
    # At 00:30 UTC.
    # Set 30 min apart from round 2 to allow enough time for any changes to propagate.
    - cron:  '30 00 * * Wed,Fri'
  repository_dispatch:
    types: update-dependencies
  workflow_dispatch:

jobs:
  update-nuget-dependencies:
    name: nanoFramework
    uses: nanoframework/nf-tools/.github/workflows/update-dependencies.yml@main
    secrets: inherit
    with:
      timeout-minutes: 180 # Non default as IoT devices has lots of solutions to update!
      solutionsToCheck: '*.sln'
      workingDirectory: devices
      branchToPr: 'develop'
      exclusionList: 'Ft6xx6x,ShiftRegister,NumberHelper,System.Buffers.Binary.BinaryPrimitives,Multiplexing,System.Device.Model,System.Diagnostics.Stopwatch,System.Drawing,System.Numerics,WeatherHelper,BoardLed,BuildHat,Common,Display,Ft232H,Ili9341,Pca9685,RGBLedMatrix,Scd4x,Seesaw,SensorHub,Sht4x,SocketCan,Ssd1351,StUsb4500,UFireIse'
